server:
  port: 8080

spring:
  redis:
    database: 3
    host: 52.80.229.82
    port: 6379
    timeout: 5000ms
    password: cot$#D4^&ddb
    lettuce:
      pool:
        max-active: 1000
        min-idle: 5
        max-wait: -1ms
        max-idle: 10
